name: WDIO Web Tests
run-name: 🧪 WDIO Web Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the tests against'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage
          - prod
      appName:
        description: 'Name of the app to test (e.g. testApp)'
        required: true
        default: 'testApp'
        type: string
      suiteName:
        description: 'Test suite name (e.g. all, e2e)'
        required: true
        default: 'all'
        type: string
      max_instances:
        description: 'Number of parallel instances to run tests (e.g. 1, 2, 3)'
        required: true
        default: '1'
        type: string

env:
  SLACK_CHANNEL: ${{vars.WDIO_SLACK_CHANNEL}}
  SLACK_WEBHOOK: ${{vars.WDIO_SLACK_WEBHOOK}}
  SLACK_USER:    ${{vars.SLACK_USER}}
  CI_PIPELINE_URL: "https://github.com/alexzavg/qa_automation_monorepo/actions/runs/${{github.run_id}}"
  TZ: ${{vars.TZ}}
  NODE_VERSION: 20.x

jobs:
  web_tests:
    runs-on: ubuntu-22.04
    env:
      REPORT_URL: https://alexzavg.github.io/qa_automation_monorepo/${{ github.event.inputs.appName }}_${{ github.event.inputs.suiteName }}_${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
          chrome-args: >
            --no-sandbox
            --disable-dev-shm-usage
            --headless
            --disable-gpu
            --window-size=1920,1080

      - name: Use node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          cd wdio
          npm install

      - name: Create .env file
        run: |
          cd wdio
          if [ "${{ github.event.inputs.environment }}" = "stage" ]; then
            echo "${{ secrets.WDIO_CONFIG_STAGE }}" > .env.stage
            echo "Created .env.stage"
          elif [ "${{ github.event.inputs.environment }}" = "prod" ]; then
            echo "${{ secrets.WDIO_CONFIG_PROD }}" > .env.prod
            echo "Created .env.prod"
          fi

      - name: Run Web tests
        run: |
          cd wdio
          export DISPLAY=:99
          ENV=${{ github.event.inputs.environment }} npx wdio run wdio.web.conf.ts \
            --appName=${{ github.event.inputs.appName }} \
            --suiteName=${{ github.event.inputs.suiteName }} \
            --maxInstances=${{ github.event.inputs.max_instances }}

      - name: Get latest build number
        if: always()
        id: get_build_number
        run: |
          SLUG="${{ github.event.inputs.appName }}_${{ github.event.inputs.suiteName }}_${{ github.event.inputs.environment }}"
          # Get the latest build number for this slug
          echo "Checking for existing builds in ${SLUG}"
          
          # First, get the directory contents
          DIR_CONTENTS=$(curl -s "https://api.github.com/repos/${{ github.repository }}/contents/${SLUG}" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}")
          
          # Check if the directory exists
          if [ -z "$DIR_CONTENTS" ]; then
            echo "No builds found yet, starting with 1"
            BUILD_NUMBER="1"
          else
            # Check if the response is an array (directory exists)
            if echo "$DIR_CONTENTS" | grep -q '"name"'; then
              # Get the latest build number
              LATEST_BUILD=$(echo "$DIR_CONTENTS" \
                | jq -r '.[] | select(.name | test("^[0-9]+$") | length > 0) | .name' \
                | sort -nr \
                | head -n 1)
              
              if [ -z "$LATEST_BUILD" ]; then
                echo "No builds found yet, starting with 1"
                BUILD_NUMBER="1"
              else
                echo "Latest build found: $LATEST_BUILD"
                BUILD_NUMBER=$(($LATEST_BUILD + 1))
                echo "New build number: $BUILD_NUMBER"
              fi
            else
              # If it's not an array, it means the directory exists but is empty
              echo "Directory exists but is empty, starting with 1"
              BUILD_NUMBER="1"
            fi
          fi
          
          echo "SLUG=$SLUG" >> $GITHUB_OUTPUT
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_OUTPUT

      - name: Deploy suite report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: wdio/html-report/allure-report
          destination_dir: ${{ steps.get_build_number.outputs.SLUG }}/${{ steps.get_build_number.outputs.BUILD_NUMBER }}

      - name: Notify Slack
        if: always()
        run: |
          STATUS="${{ job.status }}"
          COLOR="#2EB67D"
          EMOJI=":white_check_mark:"
          SLACK_TAG=""
          if [ "$STATUS" == "failure" ]; then
            COLOR="#E01E5A"
            EMOJI=":x:"
            SLACK_TAG="<${{ env.SLACK_USER }}>"
          elif [ "$STATUS" == "cancelled" ]; then
            COLOR="#808080"
            EMOJI=":black_square_for_stop:"
          fi

          BUILD_NUMBER=${{ steps.get_build_number.outputs.BUILD_NUMBER }}
          SLUG=${{ steps.get_build_number.outputs.SLUG }}
          REPORT_URL="https://alexzavg.github.io/qa_automation_monorepo/${SLUG}/${BUILD_NUMBER}"

          echo ""
          echo "🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥"
          echo "🟩 REPORT URL FOR ${STATUS^^}: ${REPORT_URL}"
          echo "🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥"
          echo ""

          curl -X POST -H 'Content-type: application/json' --data "{
            \"channel\":\"$SLACK_CHANNEL\",
            \"username\":\"Github\",
            \"attachments\":[{
              \"color\":\"$COLOR\",
              \"text\":\"$EMOJI Test suite *${{ github.event.inputs.suiteName }}* for app *${{ github.event.inputs.appName }}* on environment *${{ github.event.inputs.environment }}* finished with status *$STATUS*. :book: <${{ env.CI_PIPELINE_URL }}|LOGS>, :bar_chart: <$REPORT_URL|REPORT> $SLACK_TAG\",
              \"footer\":\"Time: $(TZ=$TZ date)\"
            }]
          }" $SLACK_WEBHOOK
